### ISSUE TITLE
Please Help , How to Setup chia miner on Arm (Raspberry pi)

### ISSUE THREAD

**Issue by dennis1511** [hpool-dev/chia-miner#247]
Hey, 
how i can run the Hpool miner on Raspberry? i have 2 files but i dont know how i can setup.

**Comment by Kayuii** [comment]
```sh
docker run -itd --rm  --name miner \
    -v "/mnt/dst:/mnt/dst" \
    -v "/opt/chia/logs:/opt/log" \
    -v "/opt/chia/config.yaml:/opt/config.yaml" \
    kayuii/hpool-miner:v1.3.0-3 hpool-chia-miner
```

default config.yaml

```yaml
path: []            #扫盘路径
minerName:          #矿机名称（自定义）
apiKey:             #hpool apikey
cachePath: ""
deviceId: ""
extraParams: {}
log:
  lv: info
  path: ./log/
  name: miner.log
url:
  info: ""
  submit: ""
scanPath: false     #是否扫盘
scanMinute: 60      #扫盘间隔（分钟）
```
