### ISSUE TITLE
linux版本的矿池怎么使用？

### ISSUE THREAD

**Issue by JaggerG** [hpool-dev/chia-miner#399]
我用的树莓派，装了ubuntu系统，运行不了arm版本的，linux那个包是使用哪个linux版本

**Comment by myVictor** [comment]
同求

**Comment by woncc** [comment]
https://github.com/hpool-dev/chia-miner/releases/download/v1.3.0-5/HPool-Miner-chia-v1.3.0-5-aarch64.zip

**Comment by JaggerG** [comment]
> 
> 
> https://github.com/hpool-dev/chia-miner/releases/download/v1.3.0-5/HPool-Miner-chia-v1.3.0-5-aarch64.zip

树莓派不是arm架构的么

**Comment by JaggerG** [comment]
> 
> 
> https://github.com/hpool-dev/chia-miner/releases/download/v1.3.0-5/HPool-Miner-chia-v1.3.0-5-aarch64.zip

想请问一下，在哪配置，还有怎么启动

**Comment by Kayuii** [comment]
```sh
docker run -itd --rm \
-v "/mnt/dst:/mnt/dst" \
-v "/opt/chia/logs:/opt/log" \
-v "/opt/chia/config.yaml:/opt/config.yaml" \
--name miner kayuii/hpool-miner:v1.3.0-5 hpool-chia-miner
```
default config.yaml
```yaml
path: [ "/mnt/dst" ]            #扫盘路径
minerName:          #矿机名称（自定义）
apiKey:             #hpool apikey
cachePath: ""
deviceId: ""
extraParams: {}
log:
  lv: info
  path: ./log/
  name: miner.log
url:
  info: ""
  submit: ""
scanPath: false     #是否扫盘
scanMinute: 60      #扫盘间隔（分钟）
```
