### ISSUE TITLE
xproxy 1.0.5代理显示容量 不显示田数量

### ISSUE THREAD

**Issue by Menglayer** [hpool-dev/chia-miner#684]
双挖日志显示正常，但是chia后台一直不计算贡献值，mass贡献值也异常

**Comment by swchang520** [comment]
Me Too

**Comment by Kayuii** [comment]
可能配置不当吧，换 linux 很稳定

**Comment by calberoni** [comment]
Same issue. I don't see any error or problem in the log files and also I did the configuration process (miner config + proxy config + plot activation in MASS wallet) twice.

Proxy config.yaml 
```
server:
    host: 192.168.1.3
    port: 9190
    url: ""
dbFile: "proxy.db"
chains:
    -
        chain: mass
        apiKey: "mass0000-xxxxxxxxxxxx"
    -
        chain: chia
        apiKey: "b208ff56-xxxxxxxxxxxxx"
```
Proxy Log:
2021/07/28 12:17:23 [I] new mining info, chain: Chia height: 635559 jobId: 4266910064 enable:true
2021/07/28 12:17:29 [I] new mining info, chain: Mass height: 1428629 jobId: 358654250 enable:true

And this is the binding_list.json created using massBindingTarget-linux. Then I've activated this plot using the wallet as the hpool tutorial shows. 
```
{
  "plots": [
    {
      "target": "14Z1B3w4S6mG6pt9AFbU7BSMopFoEhk9VvNmz",
      "type": 1,
      "size": 32
    }
  ],
  "total_count": 1,
  "default_count": 0,
  "chia_count": 1
}
```
